language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - python -m spacy download en
  - sciwing develop makedirs
  - sciwing develop download

script:
  - pytest -v -p no:warnings tests -n 4 --dist=loadfile

branches:
  only:
  - master